### ISSUE TITLE
Status Page - Erasing Dataflash does not update Available space until leave page and re-enter

### ISSUE THREAD

**Issue by BladeScraper-Designs** [rotorflight/rotorflight-lua-ethos-suite#11]
as per title.  When erasing dataflash via Status page, the available dataflash space does not update until you leave the page and go back into it.

**Comment by robthomson** [comment]
I dont believe this page has an 'auto refresh' option on it.  I will add something in.

Relatively low priority atm - will update in dev branch.

**Comment by robthomson** [comment]
Fixed
